#!/bin/bash
#while :
#do
  up=$(uptime | cut -d ',' -f1 | cut -d ' ' -f5)
  hour=$(echo $up | cut -d ':' -f1)
  min=$(echo $up | cut -d ':' -f2)
  if [ $hour -ne 0 ]; then
    echo [Uptime: ${hour}h${min}m]
  else
    echo [Uptime: ${min}m]
  fi
#done
